version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: lims_db
    environment:
      POSTGRES_USER: lims_user
      POSTGRES_PASSWORD: lims_password
      POSTGRES_DB: bloodbank_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
